<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>info_img</name>
   <tag></tag>
   <elementGuidId>f8ddbe5d-a548-4d0c-91ab-3ddb3e97210a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dialog-content > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='/assets/information.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d71965ed-ed4c-4163-91a5-e6055375ec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/fail.svg</value>
      <webElementGuid>afe1f08d-6c7b-416d-9360-5827f852e59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;modal&quot;]/dialog[1]/section[1]/div[@class=&quot;dialog-content&quot;]/img[1]</value>
      <webElementGuid>c904633a-8379-47a5-969d-691c49c67bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/img</value>
      <webElementGuid>22a93558-a37e-4161-a669-72c02638b41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/fail.svg']</value>
      <webElementGuid>58258da2-a175-43a2-9b70-212f97134381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
